Configure the content-header of template
jeroennoten/Laravel-AdminLTE pull request #918
Opened 2021-06-05 20:19 UTC by warquia

| Question                | Answer
| ----------------------- | [-----------------------]
| Issue or Enhancement    | Enhancement
| License                 | MIT

#### What's in this PR?

Allowing you to generate or not a content-header, thus allowing at 1024x768 resolutions gains more screen space,

#### Checklist

- [x] I tested these changes.
![Git](https://user-images.githubusercontent.com/7989959/120904340-1cd76d00-c622-11eb-9989-3bd8d7736d8a.jpg)

2021-06-05 20:40 UTC, resslinger requested changes
Please add a fallback, if the config var is not set.

2021-06-05 21:02 UTC, warquia reviewed
add fallback

2021-06-05 21:03 UTC, warquia commented
a

2021-06-06 00:20 UTC, Shidersz commented
@warquia what classes did you have added to the new config option you have created to get from **picture 1** to **picture 2**. If the goal is to not shown the `content-header` when the section is not used, we can do like next:

```blade
{{-- Content Header --}}
@hasSection('content-header')
    <div class="content-header">
        <div class="{{ config('adminlte.classes_content_header') ?: $def_container_class }}">
            @yield('content_header')
        </div>
    </div>
@endif
```

Also, note when you do:

```blade
<div class="{{ config('adminlte.classes_content_header_main' , 'content-header') }}">
```

the default value will only be used when the configuration option do not exists. So, when defining the option to `null` it will inject a null on the class and may result on undesired behavior. You can read [laravel docs](https://laravel.com/docs/8.x/helpers#method-config) for details. For this case, I believe it will be better to use:

```blade
<div class="{{ config('adminlte.classes_content_header_main') ?: 'content-header' }}">
```

2021-06-07 14:53 UTC, warquia commented
Good morning everyone, really has-section is the best approach, I will correct the pull-request with your analysis.
By the way, I'm new to git so I'm going to send this pull in master yet but next time I'll follow the guidance using a branch

Thank you all

2021-06-07 15:16 UTC, Shidersz requested changes
Please, do not delete `config/adminlte.php` file. Just use `git checkout config/adminlte.php` to restore it to the original one.

2021-06-07 15:18 UTC, Shidersz commented on resources/views/page.blade.php
> +            @hasSection('content_header')
Add an indent of 4 spaces to the inner code here.

2021-06-07 22:12 UTC, Shidersz approved these changes

2021-06-07 22:13 UTC, Shidersz commented
@resslinger @warquia This PR is ok for me now...

2021-06-08 06:25 UTC, resslinger approved these changes

2021-06-08 06:26 UTC, merged